'use client';

import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { auditorPortalApi } from '@/lib/api/auditor-portal';
import {
  Users, Plus, X, Copy, Check, ExternalLink, Shield,
  Clock, AlertTriangle, CheckCircle, XCircle, MessageSquare,
  Link, Trash2, RefreshCw, Sparkles, BookOpen, ArrowRight,
  Award, ChevronDown,
} from 'lucide-react';
import { cn } from '@/lib/utils';

// ─── AI Briefing Types ────────────────────────────────────────────────────────

type ControlAreaStatus = 'strong' | 'adequate' | 'needs_attention';
type ControlArea = { category: string; status: ControlAreaStatus; notes: string };
type BriefingResult = {
  companyName: string;
  frameworks: string;
  overallScore: number;
  executiveSummary: string;
  complianceOverview: string;
  scopeStatement: string;
  keyControlAreas: ControlArea[];
  policiesInPlace: string[];
  openItems: string[];
  keyContacts: string[];
  auditReadinessStatement: string;
  stats: { implemented: number; inProgress: number; notStarted: number; totalControls: number; approvedPolicies: number };
};

const CA_STATUS_CFG: Record<ControlAreaStatus, { cls: string; label: string }> = {
  strong:           { cls: 'bg-green-100 text-green-700',  label: 'Strong' },
  adequate:         { cls: 'bg-blue-100 text-blue-700',    label: 'Adequate' },
  needs_attention:  { cls: 'bg-amber-100 text-amber-700',  label: 'Needs Attention' },
};

function BriefingModal({ result, onClose }: { result: BriefingResult; onClose: () => void }) {
  const [copied, setCopied] = useState(false);

  function copyText() {
    const text = [
      `AUDIT BRIEFING PACK — ${result.companyName}`,
      `Framework: ${result.frameworks} | Readiness: ${result.overallScore}%`,
      '',
      'EXECUTIVE SUMMARY',
      result.executiveSummary,
      '',
      'COMPLIANCE OVERVIEW',
      result.complianceOverview,
      '',
      'SCOPE',
      result.scopeStatement,
      '',
      'AUDIT READINESS',
      result.auditReadinessStatement,
      '',
      'POLICIES IN PLACE',
      result.policiesInPlace.map((p) => `• ${p}`).join('\n'),
      '',
      'OPEN ITEMS',
      result.openItems.map((o) => `• ${o}`).join('\n'),
      '',
      `Generated by AI Compliance Copilot — ${new Date().toLocaleDateString()}`,
    ].join('\n');
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  return (
    <div className="fixed inset-0 bg-black/50 flex items-start justify-center z-50 overflow-y-auto py-8 px-4">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-3xl">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-100">
          <div className="flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-purple-600" />
            <div>
              <h2 className="text-base font-bold text-gray-900">AI Audit Briefing Pack</h2>
              <p className="text-xs text-gray-500">{result.companyName} · {result.frameworks} · {result.overallScore}% readiness</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button onClick={copyText} className="flex items-center gap-1.5 text-xs px-3 py-1.5 bg-gray-100 hover:bg-gray-200 rounded-lg transition-colors">
              {copied ? <><Check className="w-3.5 h-3.5 text-green-600" /> Copied!</> : <><Copy className="w-3.5 h-3.5" /> Copy all</>}
            </button>
            <button onClick={onClose} className="text-gray-400 hover:text-gray-600"><X className="w-5 h-5" /></button>
          </div>
        </div>

        {/* Content */}
        <div className="px-6 py-5 space-y-5 max-h-[75vh] overflow-y-auto">
          {/* Executive summary */}
          {result.executiveSummary && (
            <div>
              <h3 className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1.5">Executive Summary</h3>
              <p className="text-sm text-gray-800 bg-gray-50 rounded-lg p-3 border">{result.executiveSummary}</p>
            </div>
          )}

          {/* Compliance overview + scope */}
          <div className="grid grid-cols-2 gap-4">
            {result.complianceOverview && (
              <div>
                <h3 className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1.5">Compliance Overview</h3>
                <p className="text-sm text-gray-700">{result.complianceOverview}</p>
              </div>
            )}
            {result.scopeStatement && (
              <div>
                <h3 className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1.5">Scope Statement</h3>
                <p className="text-sm text-gray-700">{result.scopeStatement}</p>
              </div>
            )}
          </div>

          {/* Control areas */}
          {result.keyControlAreas.length > 0 && (
            <div>
              <h3 className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">Key Control Areas</h3>
              <div className="grid grid-cols-2 gap-2">
                {result.keyControlAreas.map((ca, i) => {
                  const cfg = CA_STATUS_CFG[ca.status] ?? CA_STATUS_CFG.adequate;
                  return (
                    <div key={i} className="border border-gray-100 rounded-lg p-2.5">
                      <div className="flex items-center gap-1.5 mb-1">
                        <span className={cn('text-xs font-medium px-1.5 py-0.5 rounded', cfg.cls)}>{cfg.label}</span>
                        <span className="text-xs font-semibold text-gray-700">{ca.category}</span>
                      </div>
                      <p className="text-xs text-gray-500">{ca.notes}</p>
                    </div>
                  );
                })}
              </div>
            </div>
          )}

          {/* Policies + open items */}
          <div className="grid grid-cols-2 gap-4">
            {result.policiesInPlace.length > 0 && (
              <div>
                <h3 className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">Policies In Place</h3>
                <ul className="space-y-1">
                  {result.policiesInPlace.map((p, i) => (
                    <li key={i} className="text-xs text-gray-700 flex gap-1.5">
                      <CheckCircle className="w-3 h-3 text-green-500 shrink-0 mt-0.5" /> {p}
                    </li>
                  ))}
                </ul>
              </div>
            )}
            {result.openItems.length > 0 && (
              <div>
                <h3 className="text-xs font-semibold text-amber-600 uppercase tracking-wide mb-2">Open Items</h3>
                <ul className="space-y-1">
                  {result.openItems.map((o, i) => (
                    <li key={i} className="text-xs text-gray-700 flex gap-1.5">
                      <AlertTriangle className="w-3 h-3 text-amber-400 shrink-0 mt-0.5" /> {o}
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </div>

          {/* Audit readiness statement */}
          {result.auditReadinessStatement && (
            <div className="bg-indigo-50 border border-indigo-100 rounded-xl p-4">
              <div className="flex items-center gap-1.5 mb-1.5">
                <Award className="w-4 h-4 text-indigo-600" />
                <h3 className="text-xs font-semibold text-indigo-700 uppercase tracking-wide">Audit Readiness Statement</h3>
              </div>
              <p className="text-sm text-indigo-800">{result.auditReadinessStatement}</p>
            </div>
          )}
        </div>

        <div className="px-6 py-3 border-t border-gray-100 bg-gray-50 rounded-b-2xl">
          <p className="text-xs text-gray-400 text-center">AI-generated draft · Review before sharing with auditors · {new Date().toLocaleDateString()}</p>
        </div>
      </div>
    </div>
  );
}

// ─── Types ────────────────────────────────────────────────────────────────────

type AuditorSession = {
  id: string;
  token: string;
  auditorName: string;
  auditorFirm?: string;
  auditorEmail?: string;
  expiresAt: string;
  isRevoked: boolean;
  lastAccessAt?: string;
  createdAt: string;
  creator: { fullName: string; email: string };
  _count: { rfis: number };
};

type AuditorRfi = {
  id: string;
  question: string;
  status: string;
  response?: string;
  priority: string;
  createdAt: string;
  control?: { code: string; title: string };
  auditorSession: { auditorName: string; auditorFirm?: string };
  responder?: { fullName: string };
};

// ─── New Session Modal ────────────────────────────────────────────────────────

function NewSessionModal({ onClose }: { onClose: () => void }) {
  const qc = useQueryClient();
  const [form, setForm] = useState({
    auditorName: '',
    auditorFirm: '',
    auditorEmail: '',
    expiresInDays: 30,
  });
  const [created, setCreated] = useState<{ token: string; auditorName: string } | null>(null);
  const [copied, setCopied] = useState(false);

  const mutation = useMutation({
    mutationFn: () => auditorPortalApi.createSession(form),
    onSuccess: (data) => {
      qc.invalidateQueries({ queryKey: ['auditor-sessions'] });
      setCreated({ token: data.token ?? '', auditorName: data.auditorName });
    },
  });

  const portalUrl = created ? `${window.location.origin}/audit/${created.token}` : '';

  function copyLink() {
    navigator.clipboard.writeText(portalUrl);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-md">
        <div className="flex items-center justify-between px-6 py-4 border-b">
          <h2 className="text-base font-semibold text-gray-900">
            {created ? 'Access Link Ready' : 'Create Auditor Access'}
          </h2>
          <button onClick={onClose}><X className="w-5 h-5 text-gray-400 hover:text-gray-600" /></button>
        </div>

        {!created ? (
          <form onSubmit={(e) => { e.preventDefault(); mutation.mutate(); }} className="px-6 py-4 space-y-4">
            <div className="text-xs text-indigo-700 bg-indigo-50 border border-indigo-100 rounded-lg px-3 py-2">
              The auditor gets a secure, read-only link — no account needed. They can browse controls, evidence, policies, and submit RFIs.
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Auditor Name *</label>
              <input required className="input w-full" placeholder="e.g. Jane Smith" value={form.auditorName}
                onChange={(e) => setForm((f) => ({ ...f, auditorName: e.target.value }))} />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Audit Firm <span className="text-gray-400 font-normal">(optional)</span></label>
              <input className="input w-full" placeholder="e.g. Deloitte" value={form.auditorFirm}
                onChange={(e) => setForm((f) => ({ ...f, auditorFirm: e.target.value }))} />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Auditor Email <span className="text-gray-400 font-normal">(optional)</span></label>
              <input type="email" className="input w-full" placeholder="auditor@firm.com" value={form.auditorEmail}
                onChange={(e) => setForm((f) => ({ ...f, auditorEmail: e.target.value }))} />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Access Duration</label>
              <select className="input w-full" value={form.expiresInDays}
                onChange={(e) => setForm((f) => ({ ...f, expiresInDays: Number(e.target.value) }))}>
                <option value={7}>7 days</option>
                <option value={14}>14 days</option>
                <option value={30}>30 days (recommended)</option>
                <option value={60}>60 days</option>
                <option value={90}>90 days</option>
              </select>
            </div>
            {mutation.isError && <p className="text-sm text-red-600">Failed to create session. Try again.</p>}
            <div className="flex gap-3 pt-1">
              <button type="button" onClick={onClose} className="btn-secondary flex-1">Cancel</button>
              <button type="submit" className="btn-primary flex-1" disabled={mutation.isPending}>
                {mutation.isPending ? 'Creating…' : 'Create Access Link'}
              </button>
            </div>
          </form>
        ) : (
          <div className="px-6 py-5 space-y-4">
            <div className="flex items-center gap-3 p-4 rounded-xl bg-green-50 border border-green-200">
              <CheckCircle className="w-5 h-5 text-green-600 shrink-0" />
              <div>
                <p className="text-sm font-semibold text-green-800">Link created for {created.auditorName}</p>
                <p className="text-xs text-green-700 mt-0.5">Share this link directly — it expires in {form.expiresInDays} days.</p>
              </div>
            </div>
            <div>
              <label className="block text-xs font-medium text-gray-500 mb-1.5">Auditor Portal Link</label>
              <div className="flex items-center gap-2">
                <input readOnly className="input text-xs font-mono flex-1 bg-gray-50" value={portalUrl} onFocus={e => e.target.select()} />
                <button type="button" onClick={copyLink} className="btn-secondary px-3 py-2 text-xs shrink-0 flex items-center gap-1.5">
                  {copied ? <Check className="w-3.5 h-3.5 text-green-600" /> : <Copy className="w-3.5 h-3.5" />}
                  {copied ? 'Copied!' : 'Copy'}
                </button>
              </div>
            </div>
            <div className="flex gap-2">
              <a href={portalUrl} target="_blank" rel="noopener noreferrer"
                className="btn-secondary flex-1 text-center text-sm flex items-center justify-center gap-1.5">
                <ExternalLink className="w-3.5 h-3.5" /> Preview portal
              </a>
              <button onClick={onClose} className="btn-primary flex-1 text-sm">Done</button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

// ─── Session Card ─────────────────────────────────────────────────────────────

function SessionCard({ session }: { session: AuditorSession }) {
  const qc = useQueryClient();
  const [copied, setCopied] = useState(false);
  const portalUrl = `${window.location.origin}/audit/${session.token}`;

  const isExpired = new Date(session.expiresAt) < new Date();
  const isActive = !session.isRevoked && !isExpired;

  function copyLink() {
    navigator.clipboard.writeText(portalUrl);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  const revoke = useMutation({
    mutationFn: () => auditorPortalApi.revokeSession(session.id),
    onSuccess: () => qc.invalidateQueries({ queryKey: ['auditor-sessions'] }),
  });

  return (
    <div className={cn(
      'bg-white border rounded-xl p-5',
      isActive ? 'border-gray-200' : 'border-gray-100 opacity-60',
    )}>
      <div className="flex items-start justify-between gap-4">
        <div className="flex items-start gap-3">
          <div className={cn(
            'w-9 h-9 rounded-full flex items-center justify-center shrink-0 text-sm font-bold',
            isActive ? 'bg-indigo-100 text-indigo-700' : 'bg-gray-100 text-gray-500',
          )}>
            {session.auditorName[0].toUpperCase()}
          </div>
          <div>
            <div className="flex items-center gap-2 flex-wrap">
              <p className="text-sm font-semibold text-gray-900">{session.auditorName}</p>
              {session.auditorFirm && <span className="text-xs text-gray-400">{session.auditorFirm}</span>}
              <span className={cn(
                'text-xs px-2 py-0.5 rounded-full font-medium',
                session.isRevoked ? 'bg-red-50 text-red-600' :
                isExpired ? 'bg-gray-100 text-gray-500' :
                'bg-emerald-50 text-emerald-600',
              )}>
                {session.isRevoked ? 'Revoked' : isExpired ? 'Expired' : 'Active'}
              </span>
            </div>
            {session.auditorEmail && <p className="text-xs text-gray-400 mt-0.5">{session.auditorEmail}</p>}
            <div className="flex items-center gap-3 mt-1 text-xs text-gray-400">
              <span className="flex items-center gap-1">
                <Clock className="w-3 h-3" />
                Expires {new Date(session.expiresAt).toLocaleDateString()}
              </span>
              <span className="flex items-center gap-1">
                <MessageSquare className="w-3 h-3" />
                {session._count.rfis} RFI{session._count.rfis !== 1 ? 's' : ''}
              </span>
              {session.lastAccessAt && (
                <span>Last accessed {new Date(session.lastAccessAt).toLocaleDateString()}</span>
              )}
            </div>
          </div>
        </div>

        <div className="flex items-center gap-2 shrink-0">
          {isActive && (
            <>
              <button
                onClick={copyLink}
                className="flex items-center gap-1.5 text-xs px-3 py-1.5 rounded-lg border border-gray-200 hover:bg-gray-50 transition-colors text-gray-600"
              >
                {copied ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
                {copied ? 'Copied!' : 'Copy link'}
              </button>
              <a
                href={portalUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="text-xs px-3 py-1.5 rounded-lg border border-gray-200 hover:bg-gray-50 transition-colors text-gray-600 flex items-center gap-1.5"
              >
                <ExternalLink className="w-3.5 h-3.5" /> Open
              </a>
              <button
                onClick={() => revoke.mutate()}
                disabled={revoke.isPending}
                className="text-xs px-3 py-1.5 rounded-lg border border-red-200 text-red-600 hover:bg-red-50 transition-colors"
              >
                Revoke
              </button>
            </>
          )}
        </div>
      </div>

      {isActive && (
        <div className="mt-3 pt-3 border-t border-gray-50 flex items-center gap-2">
          <Link className="w-3 h-3 text-gray-400 shrink-0" />
          <p className="text-xs text-gray-400 font-mono truncate">{portalUrl}</p>
        </div>
      )}
    </div>
  );
}

// ─── RFI Row ──────────────────────────────────────────────────────────────────

const RFI_STATUS_CFG: Record<string, { label: string; color: string }> = {
  open:      { label: 'Open',      color: 'bg-amber-50 text-amber-700' },
  in_review: { label: 'In Review', color: 'bg-blue-50 text-blue-700' },
  resolved:  { label: 'Resolved',  color: 'bg-emerald-50 text-emerald-700' },
  closed:    { label: 'Closed',    color: 'bg-gray-50 text-gray-500' },
};

type RfiAiResult = {
  suggestedResponse: string;
  supportingEvidence: string[];
  referencedControls: string[];
  confidenceLevel: string;
  caveats: string[];
};

const CONFIDENCE_CFG: Record<string, string> = {
  high:   'bg-green-100 text-green-700',
  medium: 'bg-amber-100 text-amber-700',
  low:    'bg-red-100 text-red-700',
};

function RfiRow({ rfi }: { rfi: AuditorRfi }) {
  const qc = useQueryClient();
  const [responding, setResponding] = useState(false);
  const [response, setResponse] = useState('');
  const [aiSuggestion, setAiSuggestion] = useState<RfiAiResult | null>(null);
  const cfg = RFI_STATUS_CFG[rfi.status] ?? RFI_STATUS_CFG.open;

  const respond = useMutation({
    mutationFn: () => auditorPortalApi.respondToRfi(rfi.id, response),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['auditor-rfis'] });
      setResponding(false);
      setResponse('');
    },
  });

  const suggestResponse = useMutation({
    mutationFn: () => auditorPortalApi.aiSuggestRfiResponse(rfi.id),
    onSuccess: (res) => {
      setAiSuggestion(res as any);
      setResponse(res.suggestedResponse ?? '');
      setResponding(true);
    },
  });

  return (
    <div className="bg-white border border-gray-100 rounded-xl p-4 space-y-2">
      <div className="flex items-start gap-3">
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-1 flex-wrap">
            <span className="text-xs font-semibold text-gray-600">{rfi.auditorSession.auditorName}</span>
            {rfi.auditorSession.auditorFirm && <span className="text-xs text-gray-400">{rfi.auditorSession.auditorFirm}</span>}
            {rfi.control && (
              <span className="text-xs font-mono text-indigo-600">{rfi.control.code}</span>
            )}
            <span className={cn('text-xs px-1.5 py-0.5 rounded-full font-medium', cfg.color)}>{cfg.label}</span>
            <span className={cn(
              'text-xs px-1.5 py-0.5 rounded-full',
              rfi.priority === 'high' ? 'bg-red-50 text-red-600' : rfi.priority === 'medium' ? 'bg-amber-50 text-amber-600' : 'bg-gray-50 text-gray-500',
            )}>
              {rfi.priority}
            </span>
          </div>
          <p className="text-sm text-gray-800">{rfi.question}</p>
        </div>
        <p className="text-xs text-gray-400 shrink-0">{new Date(rfi.createdAt).toLocaleDateString()}</p>
      </div>

      {rfi.response && (
        <div className="bg-emerald-50 border border-emerald-100 rounded-lg px-3 py-2">
          <p className="text-xs font-semibold text-emerald-700 mb-0.5">Your response</p>
          <p className="text-sm text-emerald-800">{rfi.response}</p>
        </div>
      )}

      {rfi.status === 'open' && !responding && (
        <div className="flex items-center gap-2">
          <button
            onClick={() => setResponding(true)}
            className="text-xs text-indigo-600 hover:text-indigo-700 font-medium flex items-center gap-1"
          >
            <MessageSquare className="w-3 h-3" /> Respond
          </button>
          <span className="text-gray-200">|</span>
          <button
            onClick={() => suggestResponse.mutate()}
            disabled={suggestResponse.isPending}
            className="text-xs text-purple-600 hover:text-purple-700 font-medium flex items-center gap-1 disabled:opacity-50"
          >
            {suggestResponse.isPending ? (
              <span className="w-3 h-3 border-2 border-purple-400 border-t-transparent rounded-full animate-spin" />
            ) : (
              <Sparkles className="w-3 h-3" />
            )}
            {suggestResponse.isPending ? 'Drafting…' : 'AI Draft Response'}
          </button>
        </div>
      )}

      {/* AI suggestion metadata */}
      {aiSuggestion && responding && (
        <div className="bg-purple-50 border border-purple-100 rounded-lg px-3 py-2 space-y-1.5">
          <div className="flex items-center gap-2 flex-wrap">
            <span className="text-xs font-semibold text-purple-700 flex items-center gap-1">
              <Sparkles className="w-3 h-3" /> AI suggested
            </span>
            <span className={cn('text-xs px-1.5 py-0.5 rounded', CONFIDENCE_CFG[aiSuggestion.confidenceLevel] ?? CONFIDENCE_CFG.medium)}>
              {aiSuggestion.confidenceLevel} confidence
            </span>
          </div>
          {aiSuggestion.referencedControls.length > 0 && (
            <div className="flex flex-wrap gap-1">
              {aiSuggestion.referencedControls.map((c) => (
                <span key={c} className="text-xs font-mono bg-white border border-purple-100 text-purple-600 px-1.5 py-0.5 rounded">{c}</span>
              ))}
            </div>
          )}
          {aiSuggestion.caveats.length > 0 && (
            <p className="text-xs text-amber-700">
              ⚠ {aiSuggestion.caveats[0]}
            </p>
          )}
          <p className="text-xs text-purple-600">Edit the response below before sending.</p>
        </div>
      )}

      {responding && (
        <div className="space-y-2">
          <textarea
            rows={3}
            className="input w-full text-sm resize-none"
            placeholder="Write your response…"
            value={response}
            onChange={(e) => setResponse(e.target.value)}
          />
          <div className="flex gap-2">
            <button onClick={() => respond.mutate()} disabled={!response.trim() || respond.isPending}
              className="btn-primary text-xs py-1.5 px-4">
              {respond.isPending ? 'Sending…' : 'Send Response'}
            </button>
            <button onClick={() => setResponding(false)} className="btn-secondary text-xs py-1.5 px-3">Cancel</button>
          </div>
        </div>
      )}
    </div>
  );
}

// ─── Page ─────────────────────────────────────────────────────────────────────

export default function AuditorPortalPage() {
  const [showNew, setShowNew] = useState(false);
  const [tab, setTab] = useState<'sessions' | 'rfis'>('sessions');
  const [rfiStatusFilter, setRfiStatusFilter] = useState('all');
  const [briefingResult, setBriefingResult] = useState<BriefingResult | null>(null);

  const generateBriefing = useMutation({
    mutationFn: () => auditorPortalApi.aiGenerateBriefing(),
    onSuccess: (res) => setBriefingResult(res as unknown as typeof briefingResult),
  });

  const { data: sessions = [], isLoading: sessionsLoading } = useQuery<AuditorSession[]>({
    queryKey: ['auditor-sessions'],
    queryFn: () => auditorPortalApi.listSessions() as unknown as Promise<AuditorSession[]>,
  });

  const { data: rfis = [], isLoading: rfisLoading } = useQuery<AuditorRfi[]>({
    queryKey: ['auditor-rfis'],
    queryFn: () => auditorPortalApi.listRfis() as unknown as Promise<AuditorRfi[]>,
  });

  const activeSessions = sessions.filter((s) => !s.isRevoked && new Date(s.expiresAt) >= new Date());
  const openRfis = rfis.filter((r) => r.status === 'open');
  const filteredRfis = rfiStatusFilter === 'all' ? rfis : rfis.filter((r) => r.status === rfiStatusFilter);

  return (
    <div className="p-6 space-y-5 max-w-4xl">
      {/* Header */}
      <div className="flex items-start justify-between gap-4">
        <div>
          <h1 className="text-lg font-bold text-gray-900 flex items-center gap-2">
            <Users className="w-5 h-5 text-indigo-500" />
            Auditor Portal
          </h1>
          <p className="text-xs text-gray-500 mt-0.5">
            Share secure, read-only access with your external auditors — no login required
          </p>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={() => generateBriefing.mutate()}
            disabled={generateBriefing.isPending}
            className="flex items-center gap-1.5 text-sm font-medium px-3 py-2 bg-purple-50 text-purple-700 border border-purple-200 rounded-lg hover:bg-purple-100 transition-colors disabled:opacity-60 shrink-0"
          >
            {generateBriefing.isPending ? (
              <span className="w-4 h-4 border-2 border-purple-400 border-t-transparent rounded-full animate-spin" />
            ) : (
              <Sparkles className="w-4 h-4" />
            )}
            {generateBriefing.isPending ? 'Generating…' : 'AI Briefing Pack'}
          </button>
          <button onClick={() => setShowNew(true)} className="btn-primary text-sm shrink-0">
            <Plus className="w-4 h-4 mr-1.5" /> New Access Link
          </button>
        </div>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-3 gap-3">
        {[
          { label: 'Active Sessions', value: activeSessions.length, color: 'text-emerald-600' },
          { label: 'Open RFIs', value: openRfis.length, color: openRfis.length > 0 ? 'text-amber-600' : 'text-gray-500' },
          { label: 'Total RFIs', value: rfis.length, color: 'text-gray-700' },
        ].map(({ label, value, color }) => (
          <div key={label} className="card p-4">
            <p className="text-xs text-gray-500">{label}</p>
            <p className={cn('text-2xl font-bold mt-1', color)}>{value}</p>
          </div>
        ))}
      </div>

      {/* Tabs */}
      <div className="flex gap-1 border-b border-gray-200">
        {(['sessions', 'rfis'] as const).map((t) => (
          <button
            key={t}
            onClick={() => setTab(t)}
            className={cn(
              'px-4 py-2.5 text-sm font-medium transition-colors capitalize',
              tab === t
                ? 'text-indigo-600 border-b-2 border-indigo-600'
                : 'text-gray-500 hover:text-gray-700',
            )}
          >
            {t === 'rfis' ? `RFIs${openRfis.length > 0 ? ` (${openRfis.length} open)` : ''}` : 'Sessions'}
          </button>
        ))}
      </div>

      {/* Sessions tab */}
      {tab === 'sessions' && (
        <div className="space-y-3">
          {sessionsLoading ? (
            <p className="text-sm text-gray-400 text-center py-8">Loading sessions…</p>
          ) : sessions.length === 0 ? (
            <div className="text-center py-12 bg-white border border-dashed border-gray-200 rounded-xl">
              <Shield className="w-10 h-10 text-gray-200 mx-auto mb-3" />
              <p className="text-sm font-medium text-gray-500">No auditor sessions yet</p>
              <p className="text-xs text-gray-400 mt-1">Create one to share a secure link with your auditor</p>
              <button onClick={() => setShowNew(true)} className="btn-primary text-sm mt-4">
                Create First Access Link
              </button>
            </div>
          ) : (
            sessions.map((s) => <SessionCard key={s.id} session={s} />)
          )}
        </div>
      )}

      {/* RFIs tab */}
      {tab === 'rfis' && (
        <div className="space-y-3">
          <div className="flex gap-1.5">
            {(['all', 'open', 'resolved'] as const).map((s) => (
              <button
                key={s}
                onClick={() => setRfiStatusFilter(s)}
                className={cn(
                  'px-3 py-1.5 rounded-lg text-xs font-medium transition-colors capitalize',
                  rfiStatusFilter === s ? 'bg-brand-600 text-white' : 'bg-white border border-gray-200 text-gray-600 hover:bg-gray-50',
                )}
              >
                {s === 'all' ? 'All' : s.charAt(0).toUpperCase() + s.slice(1)}
              </button>
            ))}
          </div>

          {rfisLoading ? (
            <p className="text-sm text-gray-400 text-center py-8">Loading RFIs…</p>
          ) : filteredRfis.length === 0 ? (
            <div className="text-center py-12">
              <MessageSquare className="w-8 h-8 text-gray-200 mx-auto mb-2" />
              <p className="text-sm text-gray-400">No RFIs yet. Share an access link with your auditor to get started.</p>
            </div>
          ) : (
            filteredRfis.map((r) => <RfiRow key={r.id} rfi={r} />)
          )}
        </div>
      )}

      {showNew && <NewSessionModal onClose={() => setShowNew(false)} />}
      {briefingResult && <BriefingModal result={briefingResult} onClose={() => setBriefingResult(null)} />}
    </div>
  );
}
